name: repo_viewer_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.2
  flutter_secure_storage: ^9.2.2
  dartz: ^0.10.1
  dio: ^5.1.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  webview_flutter: ^4.0.7
  flash: ^2.0.0
  auto_route: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  freezed: ^2.5.2
  auto_route_generator: ^5.0.3
  lint: ^1.5.3

flutter:
  uses-material-design: true